name: overlay_pop_up
description: A new Flutter plugin to display pop ups or screens over other apps in Android even when app is closed or killed.
version: 1.0.3
homepage: https://github.com/diegohzea/overlay_pop_up

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.requiemz.overlay_pop_up
        pluginClass: OverlayPopUpPlugin
